# Generated by Django 2.2 on 2019-05-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='userid',
            field=models.IntegerField(default=None),
        ),
    ]
